Feature
madekot/quiz pull request #2
Opened 2023-02-09 14:00 UTC by madekot

2023-02-11 13:57 UTC, kicumkicum requested changes
В целом все выглядит неплохо и стройно. Давай сделаем ещё стройнее 💪🏽

2023-02-11 13:57 UTC, kicumkicum commented on src/components/Header/Header.tsx
> +  );
Со второго захода понял. Проще будет вынести ее за пределы компонента, ведь она не использует ничего созданного внутри компонента в змыкании

2023-02-13 07:01 UTC, madekot commented on package.json
> +    "react-router-dom": "^6.8.0",
Это ты про установку пакета с флагом ?
npm i -DE package-name@1.0.1 в дев зависимости 
npm i -E package-name@1.0.1 в обычные зависимости
так пакет фиксируется намертво до package-name@1.0.**1**

2023-02-13 07:09 UTC, madekot commented on package.json
> +    "react-router-dom": "^6.8.0",
Думаю это можно быстро исправить если, удалить папку node-modules, удалить файл package-lock.json, поменять руками у всех пакетов зависимости (убрать ^) и сделать npm i.

Это проще чем каждый пакет удалять, потом ставить снова. даже если это делать одной командой. 
(npm i -DE 1package-name@1.0.1 2package-name@1.0.1 итд)
Что скажешь?

2023-02-13 07:13 UTC, madekot commented on src/App.tsx
> +}
Да согласен, думаю стоит притащить сюда editorConfig файлик с настройками. Он будет следить за правилами в новых фалах, а для старых применю пакет [eclint ](https://www.npmjs.com/package/eclint)

2023-02-13 07:16 UTC, madekot commented on src/api/index.ts
> +    IS_MESSAGE_DEBUG && console.log('эмуляция запроса на сервер: все карточки вопросов');
Хорошо, вынесу его в отдельный модуль, а в нужных местах буду вызывать функцию.

2023-02-13 07:24 UTC, madekot commented on src/api/useAllData.ts
> +  return dataMemo;
Все они используют useEffect и useState, единственное что меняется это функция, которая используется в useEffect. Можно сделать хук который будет принимать функцию, которую мы будем использовать в useEffect. 

Я хотел максимально отделить вью компоненты от их данных и логики их получения, чтобы потом можно было с минимальными правками переделать реализацию получения данных.

2023-02-13 07:29 UTC, madekot commented on src/components/Answer/Answer.tsx
> +import {useNavigate} from 'react-router-dom';
Понял, правила не сработали из за абсолютных импортов. 
[Я планировал так их сортировать](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md) "index", "sibling", "parent", "internal",  "external", "builtin", "object", "type" каждая группа отделена от предыдущей пробелом.
Думаю можно переделать на относительные импорты и сортировка с отступами может заработает

2023-02-13 07:37 UTC, madekot commented on src/components/Answer/ControlsComponent/ControlsComponent.tsx
> +          isLoading={!isLoading}
Не понял о чем ты. Лучше не выделять это в отдельный компонент, а использовать в родительском рендере и переменные в которых будут варианты кнопок?

2023-02-13 07:45 UTC, madekot commented on src/components/Header/Header.tsx
> +  );
А понял тебя, если мы вынесем её за пределы компонента, то она не будет пересоздаваться каждый раз при перерисовке компонента. 

А useCallback стоит использовать если мы передаем нашу функцию через пропс в другой компонент или возвращаем из кастомного хука. Для получения стабильной ссылки => ссылка та же перерисовки не будет

2023-02-13 07:58 UTC, madekot commented on src/components/QuestionsList/QuestionsList.tsx
> +      {Boolean(!data?.length) &&
Точно, число 0 приведется как false. Boolean() лишний, как и опциональная цепочка

2023-02-13 08:00 UTC, madekot commented on src/components/Router/RouterApp/RouterApp.tsx
> +import {PageLayout} from 'layout/PageLayout';
_Можно использовать спец символ_ Это ты про собачку? @component/ComponentName, алиасы или как их там.

2023-02-13 08:06 UTC, madekot commented on src/components/Timer/Timer.tsx
> +const START_SECOND = 15;
В принципе нормально. А как настроить линтер на эти правила? Хочется автоматизировать и не выделять внимание на такие вещи. Просто у каждой команды свои правила и привыкнув к одним тебя начнут раздражать правила другой команды, а на линтер раздражаться не получается, он еще и автоматом многое исправляет))

2023-02-13 08:19 UTC, madekot commented on src/components/Timer/usePercent.ts
> +  const [counter, setCounter] = useState(0);
Он сделан для таймера обратного отсчета времени, точнее для шкалы  визуального прогресса. 
Суть такая, он принимает общее количество секунд на вопрос в нашем случае 15 
Каждую секунду возвращает процент прогресс бара 

Сейчас думаю лучше бы он принимал не общее количество секунд, а общее количество секунд и конкретную секунду и возвращал процент её, который можно было бы использовать в прогресс баре. Или вообще без хука делать это в компоненте.

2023-02-13 08:26 UTC, madekot commented on src/components/Timer/useTimer.ts
> +export const useTimer = (startSecond: number) => {
Это счетчик, который принимает стартовое число и каждую секунду возвращает его уменьшенное на единицу, пока не достигнет нуля.

2023-02-13 08:35 UTC, madekot commented on src/helpers/isEmptyObject.ts
> +export const isEmptyObject = (obj?: object) => Boolean(!Object.values(obj || {}).length);
я использую её для отрисовки item вопроса, раньше item мог быть как объектом так и undefained, нашел только такой вариант пройти типизацию.

2023-02-13 08:35 UTC, madekot commented on src/index.tsx
> +// import {store} from './store'
Да, нужно будет найти правило на линтер для этого

2023-02-13 08:41 UTC, madekot commented on src/pages/AnswerPage/AnswerPage.tsx
> +  const item = useItemData(id);
Не понимаю, можно передать id и item параметры через пропсы, об этом?

Ну чистые функции это функции которые 
а) с одним и тем же набором параметров возвращают одинаковый результат
б) не делают побочных эффектов 
в) не мутируют входящие пропсы
г) используют только что пришло из пропсов

2023-02-13 08:42 UTC, madekot commented on src/store/redux-hooks.ts
> +export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector;
Да, все руки не доходят до RTK

2023-02-13 08:44 UTC, madekot commented on src/types/index.ts
> +export const enum RoutePath {
Про проблемы ты о циклических зависимостях?
Я думал, если у нас типы начинают использоваться в двух и более местах их лучше вынести на уровень приложения, ну или поднять на уровень где они будут необходимы)

2023-02-14 15:11 UTC, kicumkicum commented on package.json
> +    "react-router-dom": "^6.8.0",
> Это ты про установку пакета с флагом ? npm i -DE package-name@1.0.1 в дев зависимости npm i -E package-name@1.0.1 в обычные зависимости так пакет фиксируется намертво до последней цифры зависимости package-name@1.0.**1**

Да, я об этом. Это дает однозначность. Ты всегда знаешь, какая версия зависимости установлена. Плюс стабилизирует окружение, когда работаешь в команде. Не на 100 процентов стабилизирует, но сильно больше, чем без нее

2023-02-14 15:11 UTC, kicumkicum commented on package.json
> +    "react-router-dom": "^6.8.0",
> Думаю это можно быстро исправить если удалить папку node-modules, удалить файл package-lock.json, поменять руками у всех пакетов зависимости (убрать ^) в package.json и сделать npm i.
> 
> Это проще чем каждый пакет удалять, потом ставить снова. даже если это делать одной командой. (npm i -DE 1package-name@1.0.1 2package-name@1.0.1 итд) Что скажешь?

Да, это будет оптимальное решение

2023-02-14 15:12 UTC, kicumkicum commented on src/App.tsx
> +}
editorConfig хорошая штука. Там можно много чего подтюнить. И его плюс по сравнению с линтером, что он работает с любыми текстовыми файлами, а не только с js/ts

2023-02-14 15:16 UTC, kicumkicum commented on src/api/index.ts
> +    IS_MESSAGE_DEBUG && console.log('эмуляция запроса на сервер: все карточки вопросов');
По поводу тех деталей на ревью, о которых я говорил. Каждая ветка обсуждения в ПРе должна быть закрыта. Если обсуждение предполагает, что будут внесены изменения, то после внесения соответствующей правки, нужно добавить коммент done, готово, сделано. 

Так ревьювер понимает, что коммент обработан и есть код. И ты будешь легко находить комменты, где еще нужны правки

2023-02-14 15:18 UTC, kicumkicum commented on src/api/useAllData.ts
> +  return dataMemo;
> Можно сделать хук который будет принимать функцию, которую мы будем использовать в useEffect и отдавать данные

Ты мыслишь в правильном направлении

2023-02-14 15:18 UTC, kicumkicum commented on src/api/useAllData.ts
> +  return dataMemo;
> чтобы потом можно было с минимальными правками переделать реализацию получения данных

Не совсем понял, а для чего нужно будет переделывать реализацию?

2023-02-14 15:23 UTC, kicumkicum commented on src/components/Answer/Answer.tsx
> +import {useNavigate} from 'react-router-dom';
Групп достаточно много. Переносов строк будет тоже много. Если в группах будет только по одному импорту, то код будет выглядеть странно.

Вообще, по опыту, эти отступы не сильно помогают. Я бы даже сказал, что мешают. Потому что увеличивают размер блока импортов. А зависимостей зачастую получается не мало и их сложнее охватывать взглядом. Я раньше тоже разделял импорты на блоки, но потом это ушло в сторону сортировки по путям. Сортировка по путям автоматически решила эту задачу, потому что все схожие модули лежат рядом - глобальные зависимости, компоненты, сервисы. Они оказались рядом друг с другом

2023-02-14 15:29 UTC, kicumkicum commented on src/components/Answer/ControlsComponent/ControlsComponent.tsx
> +          isLoading={!isLoading}
Я об этом. Вместо условного рендеринга использовать переменные

```jsx
const text = totalQuestions === currentQuestion ? 'A' : 'B';
const to = totalQuestions === currentQuestion ? RoutePath.QUESTION_LIST : `${RoutePath.QUESTION}/${id + 1}`;

return <MyLink
        classNames={css.myLink}
        to={to}
        text={text}
        isLoading={!isLoading}
      />
```

2023-02-14 15:29 UTC, kicumkicum commented on src/components/Answer/ControlsComponent/ControlsComponent.tsx
> +          isLoading={!isLoading}
Я об этом. Вместо условного рендеринга использовать переменные

```jsx
const text = totalQuestions === currentQuestion ? 'A' : 'B';
const to = totalQuestions === currentQuestion ? RoutePath.QUESTION_LIST : `${RoutePath.QUESTION}/${id + 1}`;

return <MyLink
        classNames={css.myLink}
        to={to}
        text={text}
        isLoading={!isLoading}
      />
```

2023-02-14 15:32 UTC, kicumkicum commented on src/components/Header/Header.tsx
> +  );
> А понял тебя, если мы вынесем её за пределы компонента, то она не будет пересоздаваться каждый раз при перерисовке компонента.

Ага

> А useCallback стоит использовать если мы передаем нашу функцию через пропс в другой компонент или возвращаем из кастомного хука

Когда у нас нет возможности сделать функцию чистой и нам нужно получить в ней из замыкания переменные, созданные в теле компонента.

При этом не всегда нужно оборачивать в `useCallback` такие функции-пропсы, потому что без него код может быть проще для восприятия и при этом не сильно влиять на перерендеривание

2023-02-14 15:34 UTC, kicumkicum commented on src/components/Router/RouterApp/RouterApp.tsx
> +import {PageLayout} from 'layout/PageLayout';
Да, все верно. Только `@/component/...`. Так тебе потребуется определить только один алиас. А если `@components`, `@service`, то нужно на каждую такую директорию определять алиасы

2023-02-16 17:06 UTC, kicumkicum commented on src/types/index.ts
> +export const enum RoutePath {
> Про проблемы ты о циклических зависимостях?

Нет. Я про один большой файл с типами, которые не привязаны к какому-то контексту. Открывая такой файл ты не знаешь, что это за типы, где они используются, как связаны между собой. Придется изучать каждый тип, чтобы строить эти связи, но в своей голове. Это довольно тяжело

> Я думал, если у нас типы начинают использоваться в двух и более местах их лучше вынести на уровень приложения

Это один из вариантов. Он не самый оптимальный, потому что получаем мегафайл

> ну или поднять на уровень где они будут необходимы

Это уже лучше, но на старте все равно не понятно, куда выносить, пока слои приложения не выстроились.

Поэтому если у тебя есть в модуле тип и он кому-то потребовался, то для начала его можно просто заэкспортить из этого модуля и все. Импорты остаются логичными и понятными - если это тип роутера, значит ты зависишь от роутера. И жить так, пока не появятся циклические зависимости. Что делать дальше обсудим когда они появятся))

2023-02-16 17:11 UTC, kicumkicum commented on src/components/Timer/Timer.tsx
> +const START_SECOND = 15;
> А как настроить линтер на эти правила

Если честно, я не знаю. У меня это на подкорке)) 

Про импорты и экспорты думаю есть правила. Для всего остального не знаю. Обычно структура модуля в проектах вообще никак не регламентируется. Но у такого порядка есть обоснование, которое помогает работать с кодом. На созвоне не успели обсудить, попробуем на следующем. Записал себе

2023-02-24 09:35 UTC, madekot commented on package.json
> +    "react-router-dom": "^6.8.0",
done

2023-02-24 09:35 UTC, madekot commented on src/App.tsx
> +}
done

2023-02-24 09:35 UTC, madekot commented on src/api/index.ts
> +    IS_MESSAGE_DEBUG && console.log('эмуляция запроса на сервер: все карточки вопросов');
done

2023-02-24 09:35 UTC, madekot commented on src/api/index.ts
> +class Api {
done

2023-02-24 09:35 UTC, madekot commented on src/api/useAllData.ts
> +  return dataMemo;
done

2023-02-24 09:39 UTC, madekot commented on src/api/useAllData.ts
> +  return dataMemo;
> > чтобы потом можно было с минимальными правками переделать реализацию получения данных
> 
> Не совсем понял, а для чего нужно будет переделывать реализацию?

Я хотел потом переписать с использованием настоящего сервера. Но это не точно)

2023-02-24 10:10 UTC, madekot commented on src/components/Answer/ControlsComponent/ControlsComponent.tsx
> +          isLoading={!isLoading}
done

2023-02-24 10:16 UTC, madekot commented on src/components/QuestionsList/QuestionsList.tsx
> +
done

2023-02-24 10:30 UTC, madekot commented on src/components/Timer/usePercent.ts
> +export const usePercent = (startSecond: number) => {
done

2023-02-24 11:31 UTC, madekot commented on src/index.tsx
> +// import {store} from './store'
done

2023-02-24 11:31 UTC, madekot commented on src/layout/PageLayout/PageLayout.tsx
> +
done

2023-02-24 11:32 UTC, madekot commented on src/pages/AnswerPage/AnswerPage.tsx
> +  const item = useItemData(id);
Не понимаю

2023-02-24 11:43 UTC, madekot commented on src/components/QuestionsList/QuestionsList.tsx
> +      {Boolean(!data?.length) &&
> data типизирован как массив. Потому тут вопросик не нужен. Ну и оборачивать в Boolean тоже, потому что приведение типов

Думаю все же приведение к булевому типу нужно, если массив пустой отрисуется спинер + отрисуется 0
https://skr.sh/vIYa4KuHRU8?a

2023-02-24 11:43 UTC, madekot commented on src/components/QuestionsList/QuestionsList.tsx
> +      {Boolean(!data?.length) &&
done

2023-02-24 11:46 UTC, madekot commented on src/pages/MainMenuPage/MainMenuPage.tsx
> +        {/*<MyButton variant='outline'>показать таблицу статистики</MyButton>*/}
done

2023-02-26 10:31 UTC, kicumkicum requested changes
Круть! По таймерам я расписал. Создам ишьи для них. У меня только вопрос, по поводу однострочных функций со скобочками и `return`. Обсудим его и сольем ПР

2023-02-26 10:31 UTC, kicumkicum commented on src/components/Timer/useTimer.ts
> +export const useTimer = (startSecond: number) => {
Я смотрел на эти таймеры и они не давали мне покоя, но сформулировать прчины я не мог. На обычном ревью это не стало бы причиной остановки процесса. Я бы предложил созвониться в течении рабочего дня и мы бы все обсудили. Хотя в процессе созвона, думаю, мне бы все равно не удалось предложить более простую реализацию и мы бы слили.

Но у нас процесс академический, поэтому мне хотелось понять и объяснить, как можно сделать эту реализацию более простой для понимания. Думаю, мы не будем его исправлять в рамках этого ПРа, а перенесем в ишью, но мысли я зафиксирую здесь, чтобы не разрывать контекст.

Давай начну с проблем, которые я наблюдаю:
1. Кот в трех модулях имеет похожую структуру и вызовы. Это наводит на мысли, что где-то присутствует избыточность, от которой можно избавиться
2. Таймер прямого отсчета и таймер обратного отсчета это фактически один и тот же таймер, разница лишь в отображении. Соответственно, таймер обратного отсчета на псевдокоде должен выглядеть примерно так `const currentValue = fullSeconds - getTimerValue();`
3. Прогресс бар в общем случае на псевдокоде должен выглядеть примерно так `const percent = getTimerValue() / fullSeccond * 100;`
4. Из пунктов 2 и 3 следует, что вся реализация у нас должна быть в `getTimerValue`, а все остальное это простое вычисление, без повторения логики самого таймера
5. `useTick` вносит существенные коррективы в работу логики приложения и это путь к читам. Если внутрь него поставить `debugger`, то мы можем остановить "время" в предложении и 1 секунда может длиться бесконечно. В рамках жизненного цикла приложения это означает, что если у нас будет код, который занимает на долго поток исполнения (делает много рендеринга или вычислений), то время в приложении будет идти медленнее, чем в реальности
6. Из пункта 5 следует, что если работаешь со временем, нужно использовать настоящее время из `Date.now()` или `performance.now()` , прикладной код должен получать из него значения и возвращать остаток времени. Таким образом, если воткнуть `debugger` и подождать 5 секунд, то счетчик должен после 6 секунд отрендерить 1 секунду

Как это можно все разрулить. Фактически ответ содержится в пунктах `2, 3, 6`. Тут присутствует сложность в виде жизненного цикла реакта и функциональных компонентов. Ее нужно как-то решить, но, как я говорил, в рамках отдельной задачи по рефакторингу. В случае с классовым компонентом было бы проще, потому что мы могли записывать "чуткие" значения в свойства класса и обновлять их не влияя на рендеринг. Да и сам рендеринг был более контроллируемым. В функциональном компоненте задача усложнилась, но тем и интереснее))

2023-02-26 10:31 UTC, kicumkicum commented on src/components/Timer/useTimer.ts
> +export const useTimer = (startSecond: number) => {
- [ ] Завести issue @kicumkicum

2023-02-26 10:31 UTC, kicumkicum commented on src/components/Timer/usePercent.ts
> +  const [counter, setCounter] = useState(0);
Описал свое виденье в комментарии ниже

2023-02-26 10:31 UTC, kicumkicum commented on src/helpers/loggerMessage.ts
> +};
Интересная реализация логгера. В процессе разработки мы к нему еще вернемся и он получит хорошее развитие

2023-02-26 10:57 UTC, madekot commented on src/api/index.ts
> +        () => {return resolve(dataMock.questions);},
Это автофикс линтера, исправил. Я запретил ему сокращенную запись, вот он везде и повтыкал return. Вообще я думал он сделает форматирование по строкам. Не заметил

2023-02-26 11:23 UTC, madekot commented on package.json
> +    "fix:esLint": "npx eslint --fix src/**/*.{ts,tsx}",
done

2023-02-26 11:23 UTC, madekot commented on src/api/index.ts
> +        () => {return resolve(dataMock.questions);},
done

2023-02-26 12:15 UTC, kicumkicum approved these changes

2023-02-26 12:15 UTC, merged